zeek/zeek-docs

script-reference/statements.rst
See: https://github.com/zeek/zeek/pull/301
=> Update Docs To Reflect Key-Value For Syntax

frameworks/input.rst
This adds a bit of text to cover support for reading into sets, and
what happens when input data files aren't formatted correctly.
=> Additional documentation for the input framework

script-reference/attributes.rst
Goes with https://github.com/zeek/zeek/pull/430
=> Add &deprecation warning docs

script-reference/types.rst
Companion documentation to https://github.com/zeek/zeek/pull/431
=> Add documentation for anonymous functions with closures.

devel/style_guide.rst
This is the first cut at a coding style document for Zeek. It doesn't include any documentation on the development process. I'm opening this PR for discussion about what else we should add/remove from the document.
Related Zeek GHI: https://github.com/zeek/zeek/issues/386
=> Add coding style documentation

scripts/base/frameworks/logging/writers/ascii.zeek.rst
Documentation updates for https://github.com/zeek/zeek/pull/522
=> Add documentation for LogAscii::gzip_file_extension argument

devel/style_guide.rst
Related to namespaces and also C++17.
=> Adjust Zeek C++ style guide

examples/scripting/index.rst
Hello,
just some minor things that popped up while going through the "Writing Scripts" section.
There's a tiny bit of rewriting: If this is too much (or not correct), I can re-push with the obvious changes only.
Thanks,
Arne
=> Writing scripts minor fixes

devel/contributors/index.rst, devel/contributors/memory-checks.rst
i.e. how-to use AddressSanitizer/LeakSanitizer
Part of larger PR at https://github.com/zeek/zeek/pull/722
=> Add guide for memory error/leak checking

scripts/base/bif/zeek.bif.zeek.rst, scripts/base/init-bare.zeek.rst, scripts/policy/protocols/conn/weirds.zeek.rst
Connected to https://github.com/zeek/zeek/pull/681
=> Update docs for IOSource changes

script-reference/attributes.rst
=> Restore lost ending of &create_expire description

script-reference/types.rst
Part of https://github.com/zeek/zeek/pull/892
=> Document how alternate event/hook declarations works

quickstart/index.rst
Resolves https://github.com/zeek/zeek/issues/850
=> Add note in quickstart about using a cluster for non-trivial traffic.

frameworks/supervisor.rst, frameworks/supervisor/cluster-supervisor.zeek, scripts/base/frameworks/logging/main.zeek.rst, scripts/base/frameworks/logging/writers/ascii.zeek.rst, scripts/base/frameworks/supervisor/api.zeek.rst
Goes along with https://github.com/zeek/zeek/pull/1052
=> Supervisor doc updates

frameworks/input.rst
=> Detail differences between event and table streams

frameworks/configuration.rst
Explain that they will be called repeatedly with the same value in some circumstances.
Addresses zeek/zeek#201
=> Expand documentation of change handlers

components/index.rst, devel/plugins.rst, frameworks/input.rst, frameworks/netcontrol.rst
Btest is "A Generic Driver for Powerful System Tests",
which yields integration tests.
=> Remove references to btest as unit testing.

frameworks/notice.rst
Update docs following https://github.com/zeek/zeek/issues/214
=> Update docs with new (3.0) cluster notice-handling behavior

frameworks/logging.rst
See zeek/zeek#1189 for context
=> Documentation for the new log filter hooks

frameworks/signatures.rst
Part of this PR: https://github.com/zeek/zeek/pull/1209
=> Document "udp-state" signature condition

script-reference/types.rst
Part of https://github.com/zeek/zeek/pull/1246
=> Document behavior of integer overflows

README, install/install.rst
Part of https://github.com/zeek/zeek/pull/1312
=> Python 2 EOL maintenance

frameworks/broker.rst, script-reference/attributes.rst
Addresses https://github.com/zeek/zeek/issues/1067
=> Remove experimental language from &backend feature

install/install.rst
Companion PR to zeek/zeek#1290.
=> Cover zkg dependencies the installation docs

frameworks/notice.rst
=> Update docs for email_dest

frameworks/logging.rst, quickstart.rst
Trying to satisfy the issue #70 by adding a few lines.
=> Added a few lines describing the logdir option

devel/plugins.rst
=> GH-71: add documentation for building static plugins

script-reference/types.rst
There are additional tests for the described functionality in
https://github.com/zeek/zeek/pull/1671
Closes #67.
=> Document vector of string operations.

script-reference/statements.rst
=> Add explanation of the GLOBAL module name

frameworks/input.rst
=> Explain the input framework's new behavior re. omitted fields

scripting/basics.rst, scripting/index.rst, scripting/usage.rst
=> GH-72: Add section about script usage errors

install.rst, logs/smb.rst, logs/tunnel.rst
We should keep an eye on BZAR since we mention it prominently in our docs, since I'm not sure how continuously it's maintained.
=> A few minor edits

frameworks/logging.rst
This is based on a conversation in Slack.
=> Clarify functionality of log extension records

devel/plugins.rst
This is the companion PR to zeek/zeek-aux#22. The git comment doesn't reflect new functionality, it just seemed useful to clarify.
=> Update plugin docs to reflect init-plugin updates

frameworks/broker.rst, script-reference/statements.rst
As suggested by @anthonykasza — what do you think Anthony?
=> Add note about the need to fully quality event names in schedule statement docs

install.rst
Repo links do not work the way they are. Fixed to the working ones.
=> Fixed broken repo links

script-reference/operators.rst
Here are the documentation updates for https://github.com/zeek/zeek/pull/1999.
=> Documentation for integrating = / += / -= expressions with initializers

script-reference/types.rst
As per today's [discussion on Slack](https://zeekorg.slack.com/archives/CTGDG83B8/p1649694398602929).
@bbannier, @ynadji, please feel free to take a look, thanks.
=> Expand detail around the integer values of enum types

frameworks/index.rst, frameworks/management.rst, frameworks/management/full-config.ini, frameworks/management/get-id-value-complex.console, frameworks/management/get-id-value-simple.console, frameworks/management/mini-config-with-error.ini, frameworks/management/mini-config.ini, frameworks/management/mini-deployment-error.console, frameworks/management/mini-deployment-get-config-deployed.console, frameworks/management/mini-deployment-get-config-staged-json.console, frameworks/management/mini-deployment-get-config-staged.console, frameworks/management/mini-deployment-get-nodes.console, frameworks/management/mini-deployment.console, frameworks/management/zeek-client-help.console, frameworks/management/zeek-client-show-settings.console, frameworks/supervisor.rst
I think this is nearing completion — two sections at the end are still missing, as well as architectural diagrams, which I'm hoping to be able to complete fairly quickly tomorrow morning.
=> Document the management framework

frameworks/input.rst
https://github.com/zeek/zeek/pull/2097
=> Minor update to the input framework doc page to reflect zeek/zeek#2097

script-reference/operators.rst, script-reference/types.rst
Doc for [Add bitshift operators](https://github.com/zeek/zeek/pull/2277)
=> Add section about bitshift operators

script-reference/types.rst
=> Add docs for pattern /s modifier

frameworks/telemetry.rst
Related to
https://github.com/zeek/zeek/pull/2370
https://github.com/zeek/zeek/pull/2360
=> telemetry: Document new default behavior, reference Broker a bit more

install.rst
=> Update dependency docs to indicate needing to install Flex on macOS

script-reference/attributes.rst
This is rather sparse currently, we need to have the zeek:attr &group in place for the build to work.
=> Add &group attribute reference

cluster-setup.rst, log-formats.rst, logs/smtp.rst
...related to zeek/zeek#2401.
Closes #87
=> cluster-setup: Stab at AF_PACKET support documentation

script-reference/types.rst
Let me know if this suits.
Resolves #149.
=> Clarify the relationship of pattern type syntax to that of flex

script-reference/attributes.rst, script-reference/types.rst, scripting/usage.rst
This expands on #150 as discussed there.
Closes #150.
=> Light edits to `&is_used` and `&is_assigned`

requirements.txt
Resolves https://github.com/zeek/zeek-docs/security/dependabot/1
=> Update GitPython to resolve dependabot finding

.github/workflows/generate-docs.yml, README, install.rst
=> Bump stated Python version requirement to 3.7

install.rst
My OpenBSD fu is weak, but it Zeek installs fine for me with the command shown.
=> Mention OpenBSD in install docs, remove CentOS 8 Stream binary package example

script-reference/attributes.rst
We forgot to do so after zeek/zeek#2472.
=> Document the `&ordered` attribute

.readthedocs.yml, requirements.txt
fix as per: https://github.com/readthedocs/readthedocs.org/issues/10290#issuecomment-1535120995
Also pushed to branch `origin/devel` and build started here:
https://readthedocs.org/projects/zeek-docs/builds/20582128/
=> readthedocs: Fix urllib3/openssl issue

script-reference/attributes.rst
Closes #166
References:
zeek/zeek#3179
zeek/zeek#2668
=> attributes: Extending &default section, adding &default_insert

devel/spicy-analyzers.rst
This is a companion commit to zeek/cmake#89.
=> Mention installed Spicy analyzers in docs.

requirements.txt
Fixes https://github.com/zeek/zeek-docs/security/dependabot/3
=> Update gitpython to 3.1.34 for a security patch

conf.py
=> conf: No trailing slash for slack signup link

frameworks/logging.rst, frameworks/logging/delay1.zeek
Requires a merge of: https://github.com/zeek/zeek/pull/3471
=> Delayed log writes section

install.rst
Fixes #246. This is the docs change for https://github.com/zeek/zeek/pull/3576.
=> Remove conan from Windows install docs

install.rst
This was requested as part of the recent fixes for building against npcap. See https://github.com/zeek/zeek/pull/3678.
=> Add section about npcap to Windows build docs

frameworks/telemetry.rst, script-reference/autogenerated-script-index.rst, scripts/base/bif/comm.bif.zeek.rst, scripts/base/bif/event.bif.zeek.rst, scripts/base/bif/telemetry.bif.zeek.rst, scripts/base/frameworks/broker/main.zeek.rst, scripts/base/frameworks/cluster/main.zeek.rst, scripts/base/frameworks/telemetry/index.rst, scripts/base/frameworks/telemetry/main.zeek.rst, scripts/base/frameworks/telemetry/options.zeek.rst, scripts/base/init-bare.zeek.rst, scripts/base/init-frameworks-and-bifs.zeek.rst, scripts/base/utils/conn-ids.zeek.rst, scripts/policy/frameworks/telemetry/log.zeek.rst, scripts/policy/frameworks/telemetry/prometheus.zeek.rst
Related to https://github.com/zeek/zeek/pull/3701
=> Docs updates for telemetry rework

requirements.txt
This fixes some dependabot warnings
=> Upgrade jinja2 dependency to 3.1.5

logs/quic.rst
=> Light edits to the QUIC log intro

requirements.txt
Fixes https://github.com/zeek/zeek-docs/security/dependabot/12
=> Update jinja2 dependency to 3.1.6

script-reference/log-files.rst
(cherry picked from commit 4f6f5afdd73f6cdefaa163a854493f0b3b72d092)
Removed logs added after 7.0 was released.
=> log-files: Add logs added during the past years - for 7.0
