zeek/zeek-docs

components/index.rst, script-reference/types.rst
See: https://github.com/zeek/zeek/pull/371
Updates documentation to include new paraglob submodule and adds some additional information about opaque types to give people working on them in the future a better starting point.
The actual syntax surrounding paraglob should be finalized and it should be merged into Zeek before this is merged :)
=> Update docs for Paraglob.

conf.py
Using the supported option given by the Sphinx Read the Docs theme, adding Google Analytics support lets us have better data about who is coming to read Zeek Documentation.
=> Add Google Analytics Support

script-reference/attributes.rst
Small update to reflect the fact that `&expire_func` can take a variable number of arguments now.
=> Update &expire_func docs.

cluster/index.rst
The old link https://zeek.org/documentation/load-balancing.html is 404
=> fix the PF_RING link

examples/scripting/data_type_interval.zeek, examples/scripting/data_type_time.zeek, examples/scripting/index.rst
We accidentally swapped the conversions for month and minutes in a few places in the docs.
This PR also nukes a bunch of extraneous trailing whitespace (thanks emacs).
=> Mend month-minute mixup

script-reference/operators.rst
I didnt realize zeek had ? for months because searching docs for ternary hadn't turned it up.  So added to the section
=> add ternary operator to text

quickstart/index.rst
Script "frameworks/files/extract-all" has been changed to "frameworks/files/extract-all-files.zeek"
=> Script naming

examples/scripting/index.rst, script-reference/attributes.rst, script-reference/types.rst, scripts/base/init-bare.zeek.rst
Improved the grammar in &broker_store and in &broker_allow_complex_type prose.
Added missing semicolon on the first type in the &broker_allow_complex_type example, and added a use of  &broker_allow_complex_type  into the example.
=> Improved grammar in &broker_store and &broker_allow_complex_type and added missing semicolon

logs/conn.rst, scripting/intro.rst
This explains Zeek's "originator" and "responder" terms. It seemed to fit pretty naturally in the coverage of the connection record, but links to it also from the conn.log coverage.
=> Explain the notions of connection originator and responder

script-reference/statements.rst
This PR incorporates the function flavor comparison done in a recent blog post:
https://zeek.org/2021/06/23/functions-hooks-and-events-oh-my/
It duplicates the issue tracked as: 
https://github.com/zeek/zeek-docs/issues/60
=> Added new function flavor comparison section

devel/plugins.rst
This declares `init-plugin` deprecated for package-generation purposes, and refers to `zkg` for that purpose. `init-plugin` itself remains unchanged for the time being. We can update it accordingly, and rework these docs more broadly, for 4.2.
Resolves #64
=> Explain plugins vs packages and explain init-plugin's future role

quickstart.rst
@taosecurity I added a sentence about the Release page on GitHub copying the NEWS entry. Do you want to review this real quick?
Fixes #61
=> Add blurb about NEWS/CHANGES on the Quick Start page

script-reference/statements.rst, script-reference/types.rst
I figured out last week that functions using `return when` pass their arguments by value, not reference. Trying to document this, I ended up editing callables more broadly. Feedback welcome:
- Introduce "asynchronous function" as the name of functions that use "return
when". It looks like they didn't really have an official term yet, and
this one relates it to the broadly similar concepts e.g. in JavaScript and
Python.
- Expand the table of callable-types features to state that asynchronous
functions pass arguments by value.
- Structure the documentation of functions from one big body of text into three
sections: anonymous functions and their closures, default values, and
asynchronous functions.
- A bit of optical polish and line breaks of the callable-types table and
descriptions, with …
=> Edit pass over documentation of callable types

scripts/base/frameworks/supervisor/control.zeek.rst, scripts/policy/frameworks/cluster/agent/__load__.zeek.rst, scripts/policy/frameworks/cluster/agent/api.zeek.rst, scripts/policy/frameworks/cluster/agent/boot.zeek.rst, scripts/policy/frameworks/cluster/agent/config.zeek.rst, scripts/policy/frameworks/cluster/agent/index.rst, scripts/policy/frameworks/cluster/agent/main.zeek.rst, scripts/policy/frameworks/cluster/controller/__load__.zeek.rst, scripts/policy/frameworks/cluster/controller/api.zeek.rst, scripts/policy/frameworks/cluster/controller/boot.zeek.rst, scripts/policy/frameworks/cluster/controller/config.zeek.rst, scripts/policy/frameworks/cluster/controller/index.rst, scripts/policy/frameworks/cluster/controller/log.zeek.rst, scripts/policy/frameworks/cluster/controller/main.zeek.rst, scripts/policy/frameworks/cluster/controller/request.zeek.rst, scripts/policy/frameworks/cluster/controller/types.zeek.rst, scripts/policy/frameworks/cluster/controller/util.zeek.rst
This is the result of a manual `./ci/update-zeekygen-docs.sh` run, to speed things up today.
=> Zeekygen docs update for cluster controller documentation

script-reference/attributes.rst
This recently tripped me up in a test case that reliably took 10s despite 1s expiration intervals...
=> Clarify expiration timeout attributes

script-reference/operators.rst, script-reference/types.rst
During some performance measurements I compared this to using "add" and noticed
that this quickly gets very slow as set sizes go up (ballpark: OR-ing a
single-member set onto one with 5000 members is well north of a second).
=> Add note to call out the danger of using "set1 = set1 | set2"

script-reference/attributes.rst
While we mention this ability in the coverage of the `delete` statement, it helps to call this out here, since that's where one looks to understand the attribute.
=> Mention the ability to delete &optional fields in the attribute docs

.github/workflows/generate-docs.yml, Makefile, requirements.txt
The merge of the Management framework docs [broke](https://github.com/zeek/zeek/runs/7165231425?check_suite_focus=true) Zeek's `Generate Docs` job but works in RTD, due to a version mismatch in the pygments highlighter. It'd be nice to get a heads-up of such things prior to merging, so this runs the build via `make` in a Github action triggered on PRs.
The setup is the same as in Zeek (treat warnings as errors), but this uses built-in `sphinx-build` features for this instead of buffering the output and grepping it. If folks like this we could adopt this [in the Zeek action](https://github.com/zeek/zeek/blob/master/.github/workflows/generate-docs.yml#L90-L98) too.
To fix the failure itself, I'm bumping pygments so we test with the same version RTD currently uses.
=> Add CI to zeek-docs and bump pygments

.github/workflows/generate-docs.yml, requirements.txt
Turns out it was broken there, as @timwoj noticed.
Resolves #123.
=> Cover multiple platforms and Python versions in CI, fix macOS build

script-reference/statements.rst
I'm not 100% certain if the "core exposes value variables for free" also
applies to the vectors or is more a table/HashKey thing. Happy to
re-structure if the current version isn't quite right.
=> statements: Leave a note for index, value iteration of vectors

frameworks/supervisor.rst
I was looking into this while working on the `restart` command in the management framework.
=> Expand Supervisor docs with a section on node revival

install.rst
This adds coverage of our Docker images and restructures the section to cover dependencies only in the building-from-sources section. It now goes from easiest to most involved: Docker -> binary packages -> build from source. I've also updated some technical details that looked out of date.
This doesn't yet include AWS ECR instructions. We can add these when our images are up and running there.
RTD preview: https://docs.zeek.org/en/topic-christian-gh-134-installation/install.html
Closes #134.
=> Edit pass over installation page

cluster-setup.rst
I'm not sure this is too verbose, but given that generally seemed one
needs to find small pieces of info in various places, I'm not feeling too
bad putting a few details in.
This is mostly from a "running without zeekctl" perspective.
=> cluster-setup: Revamp Netmap section

install.rst
Verified to render correctly in my local build. Upper-casing the `c:` is just for consistency.
=> Fix blackslashes in Windows build description

frameworks/file-analysis.rst, script-reference/operators.rst
This separates general file analyzer attachment/removal concepts from subsequent examples, and expands the set of examples to include custom content analysis via the data event file analyzer. Also includes various small tweaks for better flow.
=> Expand file analysis framework docs

frameworks/management.rst, frameworks/management/zeek-client-help.console
This covers availability via `pip` and introduces some compatibility notes. Once merged we'll need to cherry-pick this into the docs release branch and bump in the Zeek release one.
=> zeek-client updates for Zeek 5.2

install.rst
=> install: Point to ./docker directory instead of Dockerfile

log-formats.rst
middle endian date format is MM-DD-YYYY so the format string and following example need to be fixed to display in that order.
=> fix middle endian date example

frameworks/broker.rst
Skimming the base scripts for proxy_topic or proxy_pool, it seems specifically base/frameworks/software uses proxy_pool unconditionally without a fallback.
I introduced that sentence recently, I'm not sure if I had picked that up elsewhere, or just assumed because mostly things work without proxies and there's no warning or so (which maybe we should add).
=> broker: Proxies aren't actually optional

ext/zeek.py
This goes with zeek/zeek#3048 to recognize the :param x: docfields and render them all into a Parameters group.
This now groups parameters into a separate section and keeps the original name in-tact.
=> ext/zeek: Support :param x: docfields

devel/spicy-analyzers.rst
We have since moved spicy-plugin into Zeek, and extended the zkg packet template.
=> Refresh Spicy analyzer docs for zeek-6.

frameworks/telemetry.rst
@timwoj - this would also need to go into the 6.0 docs. Thanks!
=> telemetry: No more Prometheus by default

devel/plugins.rst
This is part of the on-going removal of Bro naming from zkg.
=> Rename magic __bro_plugin__ file to __zeek_plugin__

conf.py
The RTD build failed with "NameError: name 'html_theme' is not defined".
Remove the conditional import and align to what Spicy and the sphinx_rtd_theme docs [1] indicate should be done.
[1] https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html
RTD build: https://readthedocs.org/projects/zeek-docs/builds/21704944/
=> conf: Add sphinx_rtd_theme to extensions, remove env based import

script-reference/types.rst
As mentioned in the discussion of https://github.com/zeek/zeek/issues/3191, the Zeek documentation is incomplete in its discussion of using the `+=` operator when the RHS is a vector compatible with the LHS. This tweak aims to remedy that.
=> Clarifying differing semantics of vector += if RHS is a compatible vector

install.rst, requirements.txt
This covers the change in OBS package naming to no longer provide packages abstractly named "zeek" and "zeek-lts", and instead shift to ones named after release trains such as "zeek-6.0".
=> Update binary package details to reflect new version labeling

frameworks/cluster.rst
and move the out-of-place proxy_pool mention around.
Closes #208.
=> cluster: Add Cluster Pool section

_templates/breadcrumbs.html
Matti noticed that these links 404'd because they omitted the file suffix. This change uses a different variable name in Jinja to fix that, and also changes the target link to the editable sources instead the default source viewer.
There's an LTD test build here if you want to check it out: https://docs.zeek.org/en/topic-christian-test-fix-github-edit-link/
Once this goes in we need it twice more, for the Broker and zkg docs.
=> Fix Github edit links in top-right of HTML pages

logs/index.rst, logs/ldap.rst
PR to add ldap.log and ldap_search.log documentation to RTD logs dir.
=> Add log page to document ldap.log and ldap_search.log

devel/spicy/autogen/zeek-functions.spicy
Goes with https://github.com/zeek/zeek/pull/3444.
=> Update for `zeek::skip_input()`.

devel/spicy/reference.rst
In the documentation for functions in Zeek's Spicy module We used links to the Spicy documentation even though these docs had moved the the Zeek docs repo as well.
=> Fix incorrect links to Spicy documentation

frameworks/management.rst
With Pygments 2.17, the TOML parser was rewritten[1, 2]. It now fails to parse and highlight the `full-config.ini` file. The key-only `agent-testbox` within `[instances]` makes the standard toml parsing barf, too. Flip to ini.
[1] https://pygments.org/docs/changelog/#version-2-17-0
[2] https://github.com/pygments/pygments/pull/2576
=> management/full-config: no toml highlighting

script-reference/types.rst
This is the companion documentation for https://github.com/zeek/zeek/pull/3416. It also includes some fledgling documentation for `table[subnet]` lookups, which as far as I can tell hasn't appeared anywhere.
=> Documentation for special table lookups (subnet or pattern index types)

script-reference/types.rst
This is quite nit-picky, forgive me — but it tones down the details a bit because I don't think it's clear to most users how one would actually construct an adversarial set of inputs to a given table. (We could explain that too, though I'm thinking that's not really necessary here.)
=> Reduce some details in the `table[pattern]` usage note

logs/ldap.rst
This PR includes two minor updates to the ldap.rst file:
1. The first instance of the term distinguished name has been updated to include its abbreviation.
2. Corrected the previously incorrect command documentation. The command `jq . ldap._search.log` has been updated to `jq . ldap.log`.
=> Fixup minor changes in the ldap.log

frameworks/signatures.rst
Not sure about the best syntax to use. It's literal brackets, so not quite sure.
=> signatures: Document custom event

install.rst
When revisiting the Windows compilation instructions recently, I briefly got hung up with a `conan`-related failure. I confirmed by reviewing the CI code at https://github.com/zeek/zeek/blob/7a9a40f822ee01cc65b8e9377c4fa087a57b2dc2/ci/windows/Dockerfile#L19C10-L19C10 that it's important to pin the `conan` version for now, so proposing to sync the docs with that. @timwoj confirmed in a [Slack thread](https://zeekorg.slack.com/archives/C04H7FMASUQ/p1703386260172159?thread_ts=1703298555.115639&cid=C04H7FMASUQ) that this docs change is probably worth making.
=> Point to conan 1.58.0 in Windows instructions

scripts/base/bif/zeek.bif.zeek.rst
Here's the companion PR to https://github.com/zeek/zeek/pull/3711.
=> Update for "footprint" documentation to reflect equating long strings with multiple objects

.github/workflows/generate-docs.yml
Python 3.7 builds aren't available on macOS ARM anymore, so CI builds will always fail. Also, Python 3.12 has come out. Python 3.13 is available but it's still only alpha builds so we can hold off on that for now.
=> CI: Remove Python 3.7, add Python 3.12

script-reference/types.rst
=> types: Document ignored &default for table[pattern] string matching

devel/spicy/tutorial.rst
This is just what I found going through the tutorial myself
1) The initial command `zeek - N Zeek::Spicy` has an extra space so that command is invalid
2) Line numbers are wrong because the `tftp.evt` file added two new lines at the top I think. Its [current state](https://docs.zeek.org/en/master/devel/spicy/tutorial.html#activating-the-analyzer) looks like:
It should (and does after this) look like:
3) Added an `import spicy;` mention since I personally prefer everything needed to compile a program being somewhere in the tutorial. It is in the [complete grammar](https://docs.zeek.org/projects/spicy/en/latest/tutorial/index.html) at the end of the spicy tutorial, though, but I prefer a mention in the zeek integration too (since it was never mentioned in the actual spicy tutorial)
=> Fix up some minor spicy tutorial docs

scripting/index.rst, scripting/optimization.rst
The goal here is to make regular users aware of the feature at this time, but leave most of the tunables and flags out of the picture for the time being.
@vpax fyi — I'm sure you'll want to iterate on this, or at least review. It's heavily based on your in-tree README, as discussed. (No rush, it can wait until you're back.)
=> Add a chapter on script optimization

devel/spicy/autogen/init-framework.zeek, devel/spicy/reference.rst, devel/spicy/tutorial.rst
This goes with https://github.com/zeek/zeek/pull/3891.
=> Documentation updates for un-deprecation of Spicy's `port`.

devel/spicy/examples/tftp-schedule-analyzer.zeek, devel/spicy/reference.rst
- convenient was misspelled
- Spicy TFTP example needs [another](https://github.com/zeek/zeek-docs/pull/275) pass, apparently there's another script that is roughly similar that still used `get_tag` :)
- Fixed up some whitespace stuff in that TFTP example - that file mixed tabs and 8 spaces so I just moved it to 4 spaces.
Fun fact: building docs fresh was fine, but when I pulled main and rebuilt it, it crashed my laptop and tried to crash it again when I retried. Like 7 python processes each taking 3GB :O
=> Fix a couple Spicy doc nits

.github/workflows/generate-docs.yml, requirements.txt
This job uses `ubuntu-latest`, i.e., it will automatically use the
newest version of Ubuntu available. On current versions `pip install`
refuses to install packages into the system since this might break
system packages. Users are expected to explicitly opt into this
potential breakage by passing the `--break-system-packages` flag. This
is an acceptable workaround here since we do not distribute this setup,
and currently things appear to not break.
=> Fix installation of Python packages in generate docs CI job

.github/workflows/generate-docs.yml
This pins the generate-docs GH workflow to run on a fixed version of ubuntu so we get defined semantics of pip install wrt system packages. We were previously using the ubuntu-latest image and GH has been switching this from ubuntu-22.04 to 24.04 and back again, also see actions/runner-images#10636.
=> Fix installation of Python packages in generate docs CI job again

.github/workflows/generate-docs.yml
Commit https://github.com/zeek/zeek-docs/commit/bd300424466d4939ef8e2eaa9936a09cbd59f1f5 removed the sudo usage
which was the actual culprit for using the wrong pip version. Bump up
to ubuntu-latest again.
=> generate-docs: Use ubuntu-latest

scripting/basics.rst
=> Add missing closing brace

log-formats.rst, logs/conn.rst, logs/dhcp.rst, logs/dpd.rst, logs/ftp.rst, logs/irc.rst, logs/pe.rst, logs/smb.rst, logs/tunnel.rst
This complements zeek/zeek#3950.
=> Documentation for conn.log's new `ip_proto` field.

README, install.rst, script-reference/statements.rst
Gets that example to ~compile~ run. Also bumps the stated Python version to 3.9 (after #285)
=> Cleanup `for` loop example + bump stated Python version

conf.py
related https://github.com/zeek/zeek/pull/4161
"by the Zeek Project" looks better to me than "The Zeek Project" and that's what Spicy docs use
=> Remove copyright year

.readthedocs.yml
RTD started enforcing the existence of this key in their yml file as of 2025/01/20. See https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/ for more info. https://readthedocs.org/projects/zeek-docs/builds/26952573/ is a build that includes the config option for testing.
Our master builds are currently failing due to the lack of this key.
=> Add sphinx configuration key for readthedocs

components/index.rst
It is probably worth it to directly link Spicy in the Zeek docs. In this patch I inserted a link above the link to binpac since today we would prefer users looking into Spicy instead binpac, but other than that I have no strong opinion on the exact order.
=> Link Spicy in subcomponent documentation

devel/spicy/autogen/zeek-functions.spicy
This is for https://github.com/zeek/zeek/pull/4346.
=> Update Spicy docs.

devel/spicy/reference.rst
This seems to be stale and no longer recommended. I did not update the analyzer examples which use it, or explanation of what happens if you do use it, since those are more prevalent and reflect current use.
For example, I still think it's useful to explain what happens to `::` in the `Analyzer::Tag` enum.
Related:
https://github.com/zeek/package-template/pull/48
https://github.com/zeek/package-template/issues/47
=> Remove `spicy::` prefix name recommendation

script-reference/types.rst
I was looking at the script types section and got annoyed. Fixes #274 
Only other section I thought would be nice to have alphabetized was [directives](https://docs.zeek.org/en/master/script-reference/directives.html), but I like `@if` and `@else` etc. being near its related parts, so I left it.
Content changes are separated to fix some minor issues I found. From what I could tell this otherwise had no significant changes, but I would appreciate a second glance in case it turns out I don't know the alphabet :)
=> Alphabetize script types section

.pre-commit-config.yaml, .typos.toml, cluster-setup.rst, devel/spicy/index.rst, frameworks/management.rst, install.rst, script-reference/operators.rst, script-reference/statements.rst, troubleshooting.rst
This ended up not being as wild as I expected. It uses a modified version of the typos.toml file from zeek/zeek. A bunch of rules from there don't matter here (such as all of the script_opt `ot` ones). There are a few new rules, but nothing wild:
- Ignore `Ninteenth`, `fo(o`, `Not-ECT`, Connection and file IDs, and a couple of strings from hexdumps in some of the logs.
- Keep it from changing "Smoot" to "Smooth"
Fixes #305
=> Add typos pre-commit rule, fix findings

get-started/install.rst, get-started/quickstart.rst
Just a couple things I noticed. The install section should probably default to showing newer releases first IMO
Random point, I waffled on the wording for this, any other suggestions? I just realized I have to use `sudo` but never mention it:
> Commands which use a network device require root access in order to monitor traffic.
=> Touchup install and quickstart

scripting/event_groups_attr_02.zeek, scripting/event_groups_module_01.zeek
This fix allows to use redefs for the options in the example code.
=> Improve event group example code

quickstart.rst
DRAFT as more feedback is gathered :)
Main things I wanted addressed:
1) Link to try.zeek.org (multiple times, in fact)
2) Use only one worker in the cluster because two is confusing
Happy to add more if any more feedback comes up. Just doing it in a draft so that PRs don't get spammed if there's more feedback
I also want to get rid of the `LogAscii::use_json=T` - but I want to get rid of it by making that default in Zeek ;)
=> Address new quickstart feedback

cluster-setup.rst
`af_packet_found_id` -> `af_packet_fanout_id` (as used in the config file directly after)
=> Fix typo in cluster config

building-from-source.rst
As of Zeek 8, ZeroMQ is no longer optional. @awelzel, @timwoj, does this look right to you?
This should go into the final Zeek 8 docs version.
=> Add ZeroMQ installation details to the building-from-source instructions
